version: '3'
services:
  gcp-service-registry:
    image: 'lawrencejews/gcp-service-registry:latest'
    container_name: gcp-service-registry
    ports:
      - '8761:8761'
  gcp-config-service:
    image: 'lawrencejews/gcp-config-service:latest'
    container_name: gcp-config-service
    ports:
      - '9296:9296'
    environment:
      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://host.docker.internal:9296/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - gcp-service-registry
  gcp-api-gateway:
    image: 'lawrencejews/gcp-api-gateway:latest'
    container_name: gcp-api-gateway
    ports:
      - '9090:9090'
    environment:
      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka
      - CONFIG_SERVER_URL=gcp-config-service
    depends_on:
      gcp-config-service:
        condition: service_healthy