server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    username: root
    password: Lubuusi@4663
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    datasource=platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296}
  zipkin:
    base-url: http://localhost:9411/zipkin/

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}